services:
  - type: worker
    name: avc-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m bot"
    runtime: python
    runtimeVersion: 3.12.7
